#ifndef FPGA_CONST_H
#define FPGA_CONST_H

#define LINUX_START_SEND_PIXEL 			1
#define LINUX_STOP_SEND_PIXEL 			2
#define FPGA_START_RECIEVE_PIXEL 		11
#define FPGA_STOP_RECIEVE_PIXEL   		12

#define LINUX_START_RECIEVE_RESULT  	3
#define LINUX_STOP_RECIEVE_RESULT 		4
#define FPGA_START_SEND_RESULT			13
#define FPGA_STOP_SEND_RESULT			14
#define FPGA_FINISH_RESULT				15

#define FPGA_IDLE						10
#define LINUX_CALL_FPGA_RESET			5
#endif